#!/usr/bin/env bash
# Analyze all DLLs/EXEs/binaries in a directory with Kong.
# Usage: ./analyze_all.sh /path/to/dlls [--jvm-heap 16g]
#
# Features:
#   - Skips binaries that already have results (resume-friendly)
#   - Skips _unpacked files (generated by Kong's auto-unpacker)
#   - Logs output per-binary for review
#   - Prints summary at the end

set -uo pipefail

DIR="${1:-.}"
shift 2>/dev/null || true
EXTRA_ARGS=("$@")  # Pass-through args like --jvm-heap 16g

if [ ! -d "$DIR" ]; then
    echo "Usage: $0 <directory> [extra kong args...]"
    echo "Example: $0 /path/to/dlls --jvm-heap 16g"
    exit 1
fi

export GHIDRA_INSTALL_DIR="${GHIDRA_INSTALL_DIR:-/opt/ghidra_11.3.2_PUBLIC}"
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk-amd64}"

shopt -s nullglob nocaseglob
files=("$DIR"/*.dll "$DIR"/*.exe "$DIR"/*.so "$DIR"/*.dylib "$DIR"/*.bin "$DIR"/*.elf)
shopt -u nullglob nocaseglob

if [ ${#files[@]} -eq 0 ]; then
    echo "No binaries found in $DIR"
    exit 1
fi

# Filter out _unpacked files (generated by Kong's auto-unpacker)
filtered=()
for f in "${files[@]}"; do
    name=$(basename "$f")
    if [[ "$name" == *_unpacked* ]]; then
        continue
    fi
    filtered+=("$f")
done
files=("${filtered[@]}")

echo "Found ${#files[@]} binaries in $DIR"
echo "---"

succeeded=0
failed=0
skipped=0
failed_names=()

for f in "${files[@]}"; do
    name=$(basename "$f")
    outdir="$DIR/kong_output_$name"
    logfile="$outdir/kong.log"

    # Skip if already has results (analysis_state.json exists with content)
    if [ -f "$outdir/analysis_state.json" ] && [ -s "$outdir/analysis_state.json" ]; then
        echo ""
        echo "=== Skipping: $name (previous results found in $outdir) ==="
        skipped=$((skipped + 1))
        continue
    fi

    echo ""
    echo "=== Analyzing: $name ==="
    mkdir -p "$outdir"

    if uv run kong analyze "$f" --headless -o "$outdir" "${EXTRA_ARGS[@]}" 2>&1 | tee "$logfile"; then
        echo "=== Done: $name ==="
        succeeded=$((succeeded + 1))
    else
        echo "=== FAILED: $name ==="
        failed=$((failed + 1))
        failed_names+=("$name")
    fi
done

echo ""
echo "========================================="
echo "  Summary"
echo "========================================="
echo "  Total:     ${#files[@]}"
echo "  Succeeded: $succeeded"
echo "  Failed:    $failed"
echo "  Skipped:   $skipped (already analyzed)"
if [ ${#failed_names[@]} -gt 0 ]; then
    echo ""
    echo "  Failed binaries:"
    for name in "${failed_names[@]}"; do
        echo "    - $name"
    done
fi
echo ""
echo "Results in $DIR/kong_output_*/"
echo "Logs in $DIR/kong_output_*/kong.log"
